@startuml Classes


class Car {
    - Brand: string
    - Name: string
    - Color: color
    - Price: int
    - Appeal: int
    - Weight: int
    - Aero: float
    + Engine
}

class Engine {
    - HP: int
    - TQ: int
}

class Dealer{

}

class Person {
    cars
    engines
    listcasrs
    listengin
}

Engine  -up-> Car
Dealer -left- Car
Person <|-- Dealer

@enduml